name: Panes
options:
  bundleIdPrefix: com.panes
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    majorVersion: 0.9.0
  Unrar:
    url: https://github.com/mtgto/Unrar.swift.git
    from: 0.3.0

targets:
  Panes:
    type: application
    platform: macOS
    sources:
      - path: Sources/Panes
        excludes:
          - "**/.DS_Store"
          - "Resources/**"
      - path: Sources/Panes/Resources
        buildPhase: resources
        excludes:
          - "**/.DS_Store"
      - path: Resources
        buildPhase: resources
        excludes:
          - "**/.DS_Store"
          - "Info.plist"
          - "AppIcon.iconset"
          - "icon_1024x1024.png"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.panes.imageviewer
        PRODUCT_NAME: Panes
        INFOPLIST_FILE: Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        COMBINE_HIDPI_IMAGES: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - package: ZIPFoundation
      - package: Unrar
